= Semantic Version for Java

Create, Parse, and Validate https://semver.org/spec/v2.0.0.html[Semantic Version 2.0.0] strings.

== Dependency

To use this library, add following dependency to your project -

.Maven Dependency
[source, xml]
----
<dependency>
  <groupId>com.github.manikmagar</groupId>
  <artifactId>semver4j</artifactId>
  <version>${semver4j.version}</version>
</dependency>
----

.Gradle Dependency
[source, groovy]
----
implementation 'com.github.manikmagar:semver4j:${semver4j.version}'
----

== Feature Implementation

- [x] Create Semantic core version (eg. 1.2.3)
- [x] Increment core Versions, examples:
** 1.2.3 -> 1.2.4
** 1.2.3 -> 1.3.0
** 1.2.3 -> 2.0.0
- [x] Validate core version
- [x] Add valid Prerelease identifiers, examples:
** 1.2.3-alpha.1
** 1.2.3-alpha.release.1
- [x] Add build metadata
- [ ] Compare Semantic versions based on specification precedence
- [ ] Parse Semantic Version strings

== Usage
Check link:src/test/java/com/github/manikmagar/semver4j/SemVerTest.java[SemVerTest.java] for all usage examples.

.SemVer Example
[source, java]
----
//Build Version 1.2.3-Alpha+Build-01
  var version = new SemVer(1, 2, 3)
    .with(prerelease("Alpha"))
    .with(build("Build-01"))
  System.out.println(version.toString())
----

== Build

Run the following command to build this project:

[source]
----
./mvnw clean verify
----

Pass the `-Dquick` option to skip all non-essential plug-ins and create the output artifact as quickly as possible:

[source]
----
./mvnw clean verify -Dquick
----

Run the following command to format the source code and organize the imports as per the project's conventions:

[source]
----
./mvnw compile -Dformat=true
----


This code base is available under the Apache License, version 2.